### ISSUE TITLE
Plugin slows down homebridge

### ISSUE THREAD

**Issue by christiantschoerner** [QuickSander/homebridge-http-curtain#16]
Homebridge gives me this error every few mintutes. My webserver responds really fast, I checked that already.

`[16/08/2021, 15:24:37] [homebridge-http-curtain] This plugin slows down Homebridge. The read handler for the characteristic 'Current Position' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[16/08/2021, 15:24:37] [homebridge-http-curtain] This plugin slows down Homebridge. The read handler for the characteristic 'Target Position' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

**Comment by QuickSander** [comment]
Hi,
This is mostly the server the plugin attempts to call is not responding. What is the target pos url you use? Do you mean you tried already to call that using wget?

**Comment by christiantschoerner** [comment]
But the server is responding really fast, thats what i meant. https://puu.sh/I4wx3/3a5595437d.png ~92ms

**Comment by QuickSander** [comment]
The url you test is a png. Try the real URL using wget. Maybe something is wrong in the URL. Please understand there is almost no special code in between making the request from HomeKit and making the HTTP request towards the server. 

What is exactly your URL specified in the config for all requests?

Why is the URL you show not a local server? Also the https I have my doubts about.

**Comment by christiantschoerner** [comment]
> The url you test is a png. Try the real URL using wget. Maybe something is wrong in the URL. Please understand there is almost no special code in between making the request from HomeKit and making the HTTP request towards the server.
> 
> What is exactly your URL specified in the config for all requests?
> 
> Why is the URL you show not a local server? Also the https I have my doubts about.

It is not about the png. It is about the response time. Even if I give the plugin a localhost server to fetch just a file that outputs "100" I get the error that the plugin slows down homebridge even if the response time is < 1ms. It is not my server that is slow - I think it is your plugin. Thats my issue

**Comment by QuickSander** [comment]
I understand your frustrations, but please allow me to help you by specifying the config including the URL's. I do not have the experience namely the plugin is slow. If it is slow, almost the only possible reason is because the call from your homebridge instance towards the remote server is slow. 

Please understand there is no magic on that code. It is just receiving the HomeKit request and making the http request. 
Do you use https? Does it eventually respond? What is your config?

Again, it is working fine on my side. Significantly less than 1ms response times from a local ESP8266 WiFi curtain device.

**Comment by QuickSander** [comment]
No response for a while, closing issue.
